databases:
  - name: spam-db
    databaseName: spam_db
    user: spam_user
    plan: free

services:
  - type: web
    name: spam-detector
    env: docker
    plan: free
    healthCheckPath: /api/stats
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: spam-db
          property: connectionString
